### ISSUE TITLE
Can you test for 'sign ups' if you keep using the same email address to sign up?

### ISSUE THREAD

**Issue by Cleop** [dwyl/byob#10]
@katbow, I wanted to do automated testing on signing up a new user. However, my assumption is that this won't work because as soon as you repeat the test then the new user will now already exist and won't be able to sign up again.

Do you know if there's any work around for this? I can intentionally test things that shouldn't work ie. if a user doesn't enter a valid password or if a user tries to sign up when they already have.

**Comment by katbow** [comment]
That's correct, if you keep trying with the same email then you should start getting errors. Is there any kind of db clear that's done at the end of the tests/after each test? 

When I'm testing the server then the db is cleared (this is built in with mix test), so I can keep using the same user data.

**Comment by Cleop** [comment]
Having discussed this with @katbow it would appear that it will not be possible to test for a complete sign up process on the live app. It is only possible to test for sign ups by clearing the db before each test and as we don't want to clear the live db (and lose record of all real users), it is not possible to repeat a sign up using the same email address repeatedly.

However, it is possible to test around the sign up procedure by checking for appropriate errors when an invalid password is entered or an already registered user attempts to sign up again.
