### ISSUE TITLE
Should screenshot files from tests be put in .gitignore?

### ISSUE THREAD

**Issue by Cleop** [dwyl/byob#15]
I'm writing automated tests for Healthlocker. In order to create a visual resource for a non-technical person to appreciate some of my tests are taking screenshots. These screenshots are over-written when the tests are re-run and so the content inside them may change. 

- Should these files be put in the .gitignore or would it be helpful for a client to be able to view the 'most recent' screenshots from when the tests were last run?

**Comment by nelsonic** [comment]
@Cleop yeah, that's what we did in [`/dwyl/learn-nightwatch/.gitignore#L15`](https://github.com/dwyl/learn-nightwatch/blob/536dca0934d1d6400c92c379f7297d6ae0a68084/.gitignore#L15)
the screenshots will change for every commit so there would be a lot of "_churn_" in Pull Requests.
