### ISSUE TITLE
Issue taking screenshot after page has fully loaded

### ISSUE THREAD

**Issue by Cleop** [dwyl/byob#5]
I am trying to wait for the page to load fully before taking a screenshot. At the moment a screenshot is taken but due to the delay created by the menu's animation, the screenshot is only capturing the menu mid-animation.

Here is the code currently:

```
const Nightmare = require('nightmare')
const nightmare = Nightmare({ show: true })


// Tests that "Home" is the innerHTML for the second 'a' tag on the menu page
nightmare.goto('https://www.healthlocker.uk/')
.click('i#open-nav')
.on('did-finish-load', ()=>{
})
.screenshot('./test/acceptance_tests/screenshots/menu.png')
.evaluate(function(){
  return document.getElementsByTagName('a')[1].innerHTML;
})
.end()
.then(function (result) {
  result == "Home" ? console.log(`Test passed: ${result} received`) : console.log(`${result} received, expected "Home"`);
})
.catch(function (error) {
  console.error('Error:', error);
});
```
If you remove the line with .on(...) then a screenshot is taken but before the page has finished loading.

The error is that .on is not a function. I tried moving .screenshot inside of .on's function to look like this:

```
.on('did-finish-load', ()=>{
  return nightmare.screenshot('./test/acceptance_tests/screenshots/menu.png')
})
```

However despite the code running, no screenshot is taken.

Perhaps there is another way to delay the taking of a screenshot to ensure a page has loaded fully? I'm hesitant to use a timeout to guesstimate the length of load time because it's unreliable.

**Comment by nelsonic** [comment]
@Cleop let's take a look at this together (_pair_) when you get into QuietSpace today. 👍

**Comment by Cleop** [comment]
Tried to solve the issue using `.wait` to wait for the screen to load certain elements: 
```
.wait('#my-sidenav a:nth-child(6)')
```

However still not getting a screenshot of the whole page. Just getting page once there is space for each of the titles:

![menu_test](https://cloud.githubusercontent.com/assets/16775804/23704339/4dd12082-03fc-11e7-9a76-a1ddc0f5d6e9.png)

**Comment by Cleop** [comment]
Tried using: 
```
.exists('#my-sidenav[style="width:100%"]') 
```
as I hoped that this would wait for the 100% width styling to have been met on my-sidenav before taking the screenshot. However this did not work in giving me the screenshot of the final page:
![menu_test](https://cloud.githubusercontent.com/assets/16775804/23707697/3626b32a-040b-11e7-8cec-0a7021272d2e.png)

**Comment by Cleop** [comment]
A solution has been found using:
```
.wait(1000) 
```

By inspecting the side nav element it became evident that there was a transition time of 0.5seconds on the .sidenav class. Therefore using wait(1000) to wait 1 second before the screenshot is taken enables the menu to be fully in place like this:

![menu_test](https://cloud.githubusercontent.com/assets/16775804/23707931/12f52ab6-040c-11e7-8382-22f2aa591c93.png)

Although initially I was doubtful about some form of timeout, given that I now know the exact transition timings of the sidenav, I am not concerned that excess time is elapsing during the test as the 1 second pause has been created specifically to accommodate the 0.5 second transition.

**Comment by nelsonic** [comment]
Great work summarising this _quest_ @Cleop ❤️  ✅
