### ISSUE TITLE
Add that you need to install nightmare as a dependency

### ISSUE THREAD

**Issue by Cleop** [dwyl/byob#9]

**Comment by Cleop** [comment]
Prior to installing nightmare:

**How should the README refer to using node?**

- dwyl has this tutorial: https://github.com/dwyl/learn-node-js-by-example
However I don't think that this tutorial is very well suited to the context within which node is needed/used for nightmare. 

- I wonder whether it's easier to simply say something along the lines of: 'nightmare runs off [node](https://nodejs.org/en/), in order to use it you must first install node. To install node ....' within the README. 

- Or you could point people to node's site and then say, once you've installed node run `npm install nightmare --save-dev`

- Or you assume that people coming to the tutorial (who are non technical) will be a client wishing to add to a project that already has node set up on it and therefore just explain to add nightmare as a dependency.

- Or link to another node tutorial like this one: http://blog.teamtreehouse.com/install-node-js-npm-mac that covers things like brew.

@nelsonic what are your thoughts?

**Comment by nelsonic** [comment]
Hi @Cleop, yes, let's _assume_ that people have node.js + NPM installed for now.
(_because they are running a ["PETE"](https://github.com/dwyl/technology-stack#the-pete-stack) project which requires node..._)
If anyone asks for clarification around the dependencies we can add to it.
